### ISSUE TITLE
Build a kit in a box docked to a station, then spawn a vessel docked to the same node, instead of the box.

### ISSUE THREAD

**Issue by allista** [allista/GroundConstruction#35]
Since it sounds like this may be within the scope of the changes you're making, I'd like to re-suggest an idea that someone posted in one of RoverDude's threads (MKS or Konstruction) awhile back: ability to extend existing vessels with GC instead of creating new ones.  Imagine a DIYKit that holds a subassembly and docks onto something like a Konstruction port before being built, and when construction is completed, it spawns the subassembly onto existing vessel.

**Comment by Wyzard256** [comment]
For reference, here's [a link to the forum post where I suggested this](https://forum.kerbalspaceprogram.com/index.php?/topic/154167-141-ground-construction/&do=findComment&comment=3387046).  And a few thoughts that come to mind based on your reply:

Instead of trying to determine whether a craft design's root part is dockable, you could require the root to be a special placeholder part that won’t actually be spawned into the world — maybe one of RoverDude's construction ports, or a new part of your own if you don't want to depend on Konstruction.  The tree of children connected to that part's bottom attachment node would be what gets grafted onto the parent vessel in place of the DIYKit.  The special root part would also serve to indicate that the craft design is intended as a subassembly for extending an existing vessel, so you could prevent players from building it standalone by mistake.

The placeholder part could also have an orientation marker on its model, which would correspond to a similar orientation marker on the DIYKit to aid the player when docking the DIYKit to the parent vessel.

KSP ignores intersections between parts on the same vessel, so you wouldn't necessarily have to "grow" the DIYKit to push things out of the way beforehand.  (It probably *can't* push other parts of the vessel, for the same reason.)  But players will still want to avoid unintended intersections, so maybe the docked DIYKit could have an option to show a preview of what the construction result will look like, similar to what KIS does when attaching a part.
