### ISSUE TITLE
Deploying docked container destroys construction vessel

### ISSUE THREAD

**Issue by fx-pain** [allista/GroundConstruction#44]
This tends to happen when weight of container and vessel are comparable. If container is big enough, fast mass shift cause it to undock/crash or even send vessel out of the solar system.
Fought it with cheats + undockig after deploy starts and redocking again (it was quite a quest).
Masses and sizes were about 100+100 tons and 150m - length of constructed vessel.

The solution I see - manage speed of deployment manually or shift mass some other way.

**Comment by allista** [comment]
The only way I see to fix this is to limit the deployment speed not by linear velocity, but by momentum, meaning that heavier kits will be deploying slower inverse-proportionally to the mass.
Current settings I came up with during the tests result in practice in deployment times about 1h for a very long (50m) 130t kit. Compared to construction times -- not so much, actually.
The fix is here: ff87b49cc5f10523b0edd87e4284785cdd79ebb2
It will be included in the next release.

**Comment by scolebrook** [comment]
FYI for anyone who has this problem even though it was fixed a long time ago, check your autostruts.

I had this problem with a very large kit and found my orbital assembly line was set to use heaviest part while all the other parts on my construction station use grandparent. The kit was the heaviest part even before deployment. As the kit grew, the autostrut would eventually tear the station apart violently. Switch it to grandparent and no problems at all. Deployment worked as normal.

Easiest way to check is to open the console (alt-f12), go to physics and check "visualize autostruts". There should be no lines connected to your kit at all.
